config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lives, only: [ :index, :show, :new, :create, :destroy] do
    resources :bookings, only: [ :new, :create ]
  end
  resources :users, only: [ :show ]
  resources :bookings, only: [ :destroy ]
    # resources :bookings, only: [ :confirm_booking, :reject_booking ]
  patch '/confirm_booking/:id', to: 'bookings#confirm_booking', as: :confirm
  patch '/reject_booking/:id', to: 'bookings#reject_booking', as: :reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :life

  # TODO add validations
end

app/models/life.rb
class Life < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  has_many :bookings, dependent: :destroy
  # TODO add validations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :lives, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @life = current_user.life
    raise
  end

  def create
    @booking = Booking.new(booking_params)  # strong params
    life = Life.find(params[:life_id])
    @booking.user = current_user
    @booking.life = life
    total_price = (@booking.end_date - @booking.start_date) * life.price_per_day
    @booking.total_price = total_price
    if @booking.save
      redirect_to user_path(current_user), notice: "Booked!"
    else
      render 'new'
    end
  end

  def confirm_booking
    # should, because we have booking from iteration
    @booking = Booking.find(params[:id])
    @booking.confirmed = 'confirmed'
    if @booking.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def reject_booking
    # should, because we have booking from iteration
    @booking = Booking.find(params[:id])
    @booking.confirmed = 'rejected'
    if @booking.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  def index
    if params[:query].present?
      @lives = Life.where("city ILIKE ?", "%#{params[:query]}%")
    else
      @lives = Life.all
    end
  end

  def show
    @life = Life.find(params[:id])
    @booking = Booking.new
  end

  def new
    @life = Life.new
  end

  def create
    @life = Life.new(life_params)
    @life.user = current_user
    if @life.save
      redirect_to life_path(@life)
    else
      render 'new'
    end
  end

  def destroy
    @life = Life.find(params[:id])
    @life.destroy
    redirect_to user_path(current_user)
  end

  private

  def life_params
    params.require(:life).permit(:description, :photo, :img_url, :price_per_day, :city, :job, :family, :relationship, :hobby)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @lives = Life.first(4)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # @lives = Life.all
    @lives = Life.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 

 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent My LIFE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <div class="page-container">
      <div class="navbar-container">
        <%= render "shared/navbar" %>
        <%= render 'shared/flashes' %>
      </div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>

  </body>
</html>

app/views/lives/index.html.erb
<div class="container-general">
  <h3>Search for the LIFE you want to experience!</h3>

  <div class="container-cards">
    <% @lives.each do |life| %>
     <div class="card-lives-all">
        <%= cl_image_tag life.photo.key, crop: :fill %>
        <div class="card-lives-content">
          <p class="text-center"><strong><%= life.user.first_name %> <%= life.user.last_name %></strong></p>
          <p><strong>City:</strong> <%= life.city %></p>
          <p><strong>Info:</strong> <%= life.description %></p>
          <p><strong>Price Per Day: </strong><%= life.price_per_day %>€</p>
        </div>
        <div class="card-lives-button">
          <% if life.user != current_user %>
            <div>
              <%= link_to "View details", life_path(life), class: "btn btn-normal" %>
            </div>
          <% else %>
            <div>
              <%= link_to "Show My Offer", life_path(life), class: "btn btn-normal" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lives/new.html.erb
<div class="container-narrow">
  <% if current_user.lives.count < 1 %>
    <div class="container-general">
      <h1>Create Your Life</h1>
      <%= simple_form_for @life, url: lives_path, method: :post do |f| %>
        <%= f.input :description, placeholder: "please describe your life!" %>
        <%= f.label "Profile Photo" %>
        <br>
        <%= f.file_field :photo, direct_upload: true %><br><br>
        <%= f.input :price_per_day %>
        <%= f.input :city %>
        <%= f.input :job %>
        <%= f.input :family %>
        <%= f.input :relationship %>
        <%= f.input :hobby %>
        <br>
        <%= f.submit class: "btn btn-normal" %>
      <% end %>
    </div>
  <% else %>
    <div class="container-general text-center">
      <h1>You can only offer one life!</h1>
      <br>
      <p>If you want to create a new offer, please <%= link_to "delete your life first", life_path(current_user) %>.<p>
    </div>
  <% end %>
</div>

app/views/lives/show.html.erb
<div class="container-general">

  <h1>The Life of <%= @life.user.first_name %></h1>
  <br>
  <br>
  <div class="container-life d-flex">
    <div class="image text-center">
      <%= cl_image_tag @life.photo.key, width: 250, height: 300, crop: :fill %>
    </div>
    <div class="text-life">
      <p><strong>Name: </strong><%= @life.user.first_name %> <%= @life.user.last_name %></p>
      <p><strong>City:</strong> <%= @life.city %></p>
      <p><strong>Info:</strong> <%= @life.description %></p>
      <p><strong>Job:</strong> <%= @life.job %></p>
      <p><strong>Family:</strong> <%= @life.family %></p>
      <p><strong>Relationship:</strong> <%= @life.relationship %></p>
      <p><strong>Hobby:</strong> <%= @life.hobby %></p>
      <p><strong>Price per day:</strong> <%= @life.price_per_day %>€</p>
    </div>
  </div>
  <br>
  <br>

  <% if @life.user != current_user %>
    <div class="container-life-booking">
      <div class="form-wrapper" style="width: 400px;">
        <h2>Book This Life</h2>
        <br>
        <%# TODO somehow the start_date lines will be dublicated when clicked on go-back in browser %>
        <%= simple_form_for [@life, @booking], url: life_bookings_path(@life), method: "post" do |f| %>
          <p>Cost: <%= @life.price_per_day %> € / day</p>
          <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"} %>
          <br>
          <%= f.submit class: "btn btn-normal", placeholder: 'Book now!' %>
        <% end %>
      </div>
    </div>
  <% else %>
    <%= link_to "Cancel my offer", life_path(@life), class: "btn btn-normal", method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="banner">
    <div class="container container-banner">
      <h1>What is your Dream LIFE? find out!</h1>
      <%= link_to "Book your first LIFE now!", lives_path, class: "btn btn-large" %>
      <div class="searchbar">
        <%= form_tag lives_path, method: :get do %>
          <%= label_tag "city" %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search..."
            %>
            <%= button_tag(type: "submit", class: "btn btn-default") do %>
              <i class="fas fa-search"></i>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-header">
    <h1><strong>Our top lives</strong></h1>
    <h4>Get inspired and book your next life</h4>
    <%# <h1><strong>Inspiration for future LIFE</strong></h1> %>
    <%# <h4>Lives to book with your upcoming experience</h4> %>
  </div>
  <div class="card">
    <% @lives.each do |life| %>
      <div class="card-life">
        <%= cl_image_tag life.photo.key, crop: :fill %>
        <div class="card-content">
          <h5 class="card-title">
            <%= life.user.first_name %> <%= life.user.last_name %>
          </h5>
          <p class="card-text">
            <p class="city">
              <strong>City:</strong> <%= life.city.capitalize %>
            </p>
            <p class="info">
              <strong>Info:</strong> <%= life.description.capitalize %>
            </p>
          </p>
          <%= link_to "Book now", life_path(life), {:class => "btn btn-normal"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-logo">
    <%= cl_image_tag("https://res.cloudinary.com/rentmylife/image/upload/v1614249655/assets/Logo_new_ujtxee.png") %>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> from Batch 530
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= cl_image_tag("https://res.cloudinary.com/rentmylife/image/upload/v1614249655/assets/Logo_new_ujtxee.png") %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Browse Lives", lives_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Become Host", new_life_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item" id="avatar-items">
        <%= link_to current_user.first_name, user_path(current_user), class: "nav-link" %>

          <% if current_user.photo.attached? %>
            <%= link_to cl_image_tag(current_user.photo.key), user_path(current_user), class: "avatar" %> 
          <% else %>
            <%= link_to cl_image_tag("https://res.cloudinary.com/rentmylife/image/upload/v1614335184/kisspng-computer-icons-person-avatar-download-person-icon-5b480703d1f604.21741917153144704386_foan5y.png"), user_path(current_user), class: "avatar" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-narrow">
  <div class="container-profile">
    <%# USER-PROFILE %>
    <h1>Hi <%= current_user.first_name %> 👋🏼</h1>
    <br>
    <div class="user-profile">
        <p><strong>Email:</strong> <%= @user.email %></p>
        <p><strong>Address:</strong> <%= @user.address %></p>
        <p><strong>Age:</strong> <%= @user.age %></p>
        <p><strong>Gender:</strong> <%= @user.gender %></p>
        <p><strong>Bio:</strong> <%= @user.host_bio %></p>
      <br>


    <%# UPDATE-PROFILE %>
      <div>
        <%= link_to "Edit profile", edit_user_registration_path(current_user), class: "btn btn-normal" %>
      </div>
    </div>
  </div>

  <%# PENDING BOOKINGS %>
  <div class="container-profile">
    <h2>Pending Bookings</h2>
    <br>
    <% if @bookings.where(confirmed: 'pending').empty? %>
      <p>No pending lifes</p>
    <% else %>

      <% @bookings.each do |booking| %>
        <% if booking.confirmed == 'pending' %>
          <div class="card-product">
            <div class="d-flex justify-content-between w-100 align-items-center">
              <div class="d-flex justify-content-start">
                <%= cl_image_tag booking.life.photo.key, crop: :fill %>
                <div class="card-product-infos">
                  <h2><%= booking.life.user.first_name %> <%= booking.life.user.last_name %></h2>
                  <p><strong>Job:</strong> <%= booking.life.job %></p>
                  <p><strong>Family:</strong> <%= booking.life.family %></p>
                  <p><strong>City:</strong> <%= booking.life.city %></p>
                  <p><strong>Total price: </strong><%= booking.total_price %> €</p>
                </div>
              </div>
            <%# TODO not functional %>
            <div>
              <%= link_to "Cancel", booking_path(booking), class: "btn btn-normal mr-3", method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>


  <%# CONFIRMED BOOKINGS %>
  <div class="container-profile">
    <h2>Confirmed Bookings</h2>
    <br>
    <% if @bookings.where(confirmed: 'confirmed').empty? %>
      <p>No booked lifes</p>
    <% else %>
      <% @bookings.each do |booking| %>
        <% if booking.confirmed == 'confirmed' %>
          <div class="card-product">
            <div class="d-flex justify-content-between w-100 align-items-center">
              <div class="d-flex justify-content-start">
                <%= cl_image_tag booking.life.photo.key, crop: :fill %>
                <div class="card-product-infos">
                  <h2><%= booking.life.user.first_name %> <%= booking.life.user.last_name %></h2>
                  <p><strong>Job:</strong> <%= booking.life.job %></p>
                  <p><strong>Family:</strong> <%= booking.life.family %></p>
                  <p><strong>City:</strong> <%= booking.life.city %></p>
                  <p><strong>Total price: </strong><%= booking.total_price %> €</p>
                </div>
                <%# TODO not functional %>
                <div>
                  <%= link_to "Cancel", booking_path(booking), class: "btn btn-normal mr-3", method: :delete, data: { confirm: "Are you sure?" } %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%# MY-LIVES %>
  <div class="container-profile">
    <h2>My offered Life</h2>
    <br>
    <% if @lives.empty? %>
      <p>No life. Go and create your first one! The button is in the navbar :)</p>
    <% else %>
      <% @lives.each do |life| %>
        <div class="card-product">
          <div class="d-flex justify-content-between w-100 align-items-center">
            <div class="d-flex justify-content-start">
              <%= cl_image_tag life.photo.key, crop: :fill %>
              <div class="card-product-infos">
                <h2><%= life.user.first_name %> <%= life.user.last_name %></h2>
                <p><strong>Job:</strong> <%= life.job %></p>
                <p><strong>Family:</strong> <%= life.family %></p>
                <p><strong>City:</strong> <%= life.city %></p>
                <p><strong>Price Per Day: </strong><%= life.price_per_day %>€</p>
              </div>
            </div>
            <div>
              <%= link_to "Cancel", life_path(life), class: "btn btn-normal mr-3", method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <%# Pending Bookings of my life %>
  <div class="container-profile">
    <h2>Pending bookings of my life</h2>
    <br>
    <% if @lives.empty? %>
      <p>No pending lifes</p>
    <% else %>
      <% @lives.each do |life| %>
        <% life.bookings.each do |booking| %>
          <% if booking.confirmed == 'pending' %>
            <div class="card-product">
              <div class="d-flex justify-content-between w-100 align-items-center">
                <div class="d-flex justify-content-start">
                <%= cl_image_tag life.photo.key, crop: :fill %>
                  <div class="card-product-infos">
                    <h2><%= life.user.first_name %> <%= life.user.last_name %></h2>
                    <p><strong>Job:</strong> <%= life.job %></p>
                    <p><strong>Family:</strong> <%= life.family %></p>
                    <p><strong>City:</strong> <%= life.city %></p>
                    <p><strong>Price Per Day: </strong><%= life.price_per_day %>€</p>
                  </div>
                </div>
                <%# accept is functional %>
                <div>
                  <%= link_to "Accept", confirm_path(booking), class: "btn btn-green", method: :patch, data: { confirm: "Are you sure?" } %>

                  <%= link_to "Reject", reject_path(booking), class: "btn btn-normal mr-3", method: :patch, data: { confirm: "Are you sure?" } %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%# Booked Bookings of my life %>
  <div class="container-profile">
    <h2>Bookings of my life</h2>
    <br>
    <% if @lives.empty? %>
      <p>No bookings so far</p>
    <% else %>
      <% @lives.each do |life| %>
        <% life.bookings.each do |booking| %>
          <% if booking.confirmed == 'confirmed' %>
            <div class="card-product">
              <div class="d-flex justify-content-between w-100 align-items-center">
                <div class="d-flex justify-content-start">
                <%= cl_image_tag life.photo.key, crop: :fill %>
                  <div class="card-product-infos">
                    <h2><%= life.user.first_name %> <%= life.user.last_name %></h2>
                    <p><strong>Job:</strong> <%= life.job %></p>
                    <p><strong>Family:</strong> <%= life.family %></p>
                    <p><strong>City:</strong> <%= life.city %></p>
                    <p><strong>Price Per Day: </strong><%= life.price_per_day %>€</p>
                  </div>
                </div>
                <%# TODO not functional %>
                <div>
                  <%= link_to "Cancel", reject_path(booking), class: "btn btn-normal mr-3", method: :patch, data: { confirm: "Are you sure?" } %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>